### ISSUE TITLE
Installation instructions in README

### ISSUE THREAD

**Issue by vladimir-v-diaz** [awwad/uptanedemo#30]
The README instructs the user to `sudo apt-get python3-dev`, but the provided command for virtualenv uses python 2.

**Comment by awwad** [comment]
The instruction includes both the headers for Python2 and Python3:
sudo apt-get install build-essential libssl-dev libffi-dev **python-dev python3-dev**

At the moment, the services run in Python2 so that the ASN.1 conversion works, and the web frontend runs in Python3 due to its own dependency issues. Once the rest of the ASN.1 code has been revised, it should run in Python3, too.

**Comment by vladimir-v-diaz** [comment]
I see.  Perhaps the second paragraph of your reply can be added somewhere in the README so that others are aware.

**Comment by awwad** [comment]
I'll add something to the README. The web frontend doesn't figure anywhere in the readme or the repo. It's external for now. So the Python2 and Python3 instructions are there mostly so that if versions are switched, the installation doesn't need to change.

**Comment by awwad** [comment]
This issue was moved to uptane/uptane#28
